### ISSUE TITLE
MQTT nodes

### ISSUE THREAD

**Issue by ZhenyaRUS39** [xodio/xod#1391]
I propose to consider the possibility of making a nodes interaction with MQTT broker. MQTT is now very convenient in the Internet of things. Creating an MQTT nodes will greatly simplify the development of the Internet of things with XOD. The code and logic for conversion can be found in the MQTT Arduino library.

**Comment by nkrkv** [comment]
Although I agree on MQTT might be very useful for IoT applications, I have to close the issue because XOD uses GitHub issues as a task tracker, not a discussion platform. That is, every issue must have a notion of completeness and accepted for implementation.

For discussions, please start a new topic on https://forum.xod.io. I’ll gladly continue the discussion there. And once we agree on the node list and their details, a new issue on GitHub might be created.
