### ISSUE TITLE
Yarn fails on inital run

### ISSUE THREAD

**Issue by Kilill** [xodio/xod#1455]
## Bug Report 

Running yarn on a initial setup
fails with : 

error An unexpected error occurred: "https://registry.yarnpkg.com/@glennsl/rebase/-/rebase-0.2.0.tgz: ESOCKETTIMEDOUT".

### Environment
-  Ubuntu 17.10

### Steps to reproduce
clone Xod from git
enter xod directory
run yarn

### Expected behavior
Yarn should complete without errors

**Comment by nkrkv** [comment]
Hello and thank you for reporting.

Just tried to reproduce now. Can’t reproduce. Yarn install modules fine.

The error might be related to a (very rare) Yarn/NPM index outage. Could you try again? What happens if you try to open the link <https://registry.yarnpkg.com/@glennsl/rebase/-/rebase-0.2.0.tgz> in a web browser?

**Comment by Kilill** [comment]
That was one of the first things i  tried, which just hang for a long time, thinking it might be a server outage i waited half an hour or so, still nothing, but ofc today that worked like  a charm, still failed on node not being >= v8 though. Seems Ubuntu ships with an ancient node install. Removed it and reinstalled according to : https://github.com/nodesource/distributions , might want to mention that in the readme...

Anyways, install completed and everything seems to be running smoothly so this issue can be closed
