### ISSUE TITLE
tabtests transpile pin names with - (dash) instead of _ (underscore)

### ISSUE THREAD

**Issue by awgrover** [xodio/xod#1664]
### Environment

* Scope: desktop IDE
* Version: 0.26.1
* OS: Ubuntu 16.04
* Machine:x86_64, 32 GB RAM

### Steps to reproduce

1. Create a patch with an input named "a-a" (anything with a dash)
1. Add a tabtest
1. Add a row to tabtest, use the name "a-a"
1. Try to run the tab test
1.You'll get a c++ compile error something like this:
```
/wait-all.catch.inl:6:7: error: declaration of variable 'probe_bit' with deduced type 'auto &' requires an initializer
auto& probe_bit-count = xod::node_15;
      ^
./wait-all.catch.inl:6:16: error: expected ';' after top level declarator
auto& probe_bit-count = xod::node_15;
               ^
```

### Expected behavior

The tabtest should use the pin-name.
If you can set the pin name to something, then it should work everywhere.

### Actual behavior

c++ compile error as above.

### Console output 

above

### How to fix 

I think the pin names should be made c++ safe by changing - (dash) to _ (underscore). You have some other issues (cf. #491) that are moving toward the prohibition of dash and underscore.

Dashes make names easier to read. I would hate to see dashes go away.

it feels like pin-names (and patch-names) are used in the c++ code inconsistently. Assuming there is an object for the pin, there should be a cpp_name() method used when generating c++ code. In js it should be just
```
pin_name.replace( /-/, '_' )
```

**Comment by nkrkv** [comment]
Thank you for the detailed report. The scope is wider than tabtests, it is related to using any non-ASCII characters for pin names which should be transpiled to C++. To properly fix it, I suggest performing the following substitutions:

| Pin name char | C++ replacement |
| ------- | ------- |
| ` ` (space) | `_` |
| `-` | `_` |
| `δ` (custom unicode) | `U03B4` (UTF sequence) |
| `🙀` (custom rare unicode) | `U1F640` |

Given that a C++ xoder might use the following to read from a pin named `δ 1`:

```cpp
getValue<input_U03B4_1>(ctx);
```

or he might make a macrodefinition to make the code more readable

```cpp
#define input_delta_1 input_U03B4_1

// ...

getValue<input_delta_1>(ctx);
```

XOD IDE should change there are no conflicts in patch terminal names so that having the following pairs at once should render an error:

- `a_b`, `a-b`
- `δ`, `U03B4`
