### ISSUE TITLE
Crystal LCD display doesnot accept unicode

### ISSUE THREAD

**Issue by EdenMelaku** [xodio/xod#1901]
### Environment
Windows10, XOD 0.311.1.
### Actual behavior
displays the letter a

do i have to modify the code to translate the characters to ascii then to send it to the device? if so which module do i have to modify?

**Comment by nkrkv** [comment]
~It’s not a bug, but a feature~

Well, the problem is with encoding differences. LCDs can only show a very limited set of characters (~256, some ~512) which is way less the number of chars in Unicode. So supporting Unicode within `xod-dev/text-lcd` is nearly impossible.

Another question is why it does not show `Пендель` even if the chartable inside it is capable of displaying it. That’s because C++ stores strings in UTF-8 whereas LCD uses CP1251 or something like that. Which are totally different encodings.

Perhaps, we XOD can offer encoding selection for static string literals in the future.

For now, you have to look at LCD code page (in its datasheet) and enter the necessary characters in `\x##` notation. See https://xod.io/docs/guide/text-lcd/#special-characters
