### ISSUE TITLE
There is no constant-color?

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1969]
In the new version I do not see constant color.

I thought it would be good to replace constants with tweak, but making a constant-number vs tweak-number comparison there is an increase of 48 bytes (682 vs 730)

**Comment by nkrkv** [comment]
It was never being there. Since `color` is a [not-so] regular custom type and not a built-in type it lacks some features of the built-in types. For now, either bind value directly or use a component-based constructor: `color-rgb`, `color-hsl`, or `color-rgb-bytes`.

However, I agree, there might be a node for `color` which has a single output which is bindable. Issued #1970 for that.
