### ISSUE TITLE
Investigate software licensing issues.

### ISSUE THREAD

**Issue by alexander-matsievsky** [xodio/xod#336]
Primarily, inter-operating with GPL-licensed DIY tool-chains.

**Comment by Gamadril** [comment]
I hope you investigate more time on the license issue. Because IMHO with AGPL you are doomed to fail. Not only that you are using a lot of 3rd party libraries in your code that are incompatible with GPL, you force everyone who wants to use your software to release the full source code. And any module/extension has to be GPL licensed as well.

**Comment by nkrkv** [comment]
> you are using a lot of 3rd party libraries in your code that are incompatible with GPL

Could you provide an example? MIT, BSD, LGPL *are* compatible with AGPL.

> you force everyone who wants to use

Not quite. Only those who want to *redistribute* should release the code. That’s the point of GPL. Regular xoders may use XOD without any problems.

**Comment by Gamadril** [comment]
You are right MIT, Apache 2.0. and BSD are compatible with the latest GPLv3. At least they allow adding their code in GPLv3 projects.
Sorry, misunderstanding of word "use"... I thought here about hosting a modified version (changing CSS styles is a modification) of XOD IDE with support of additional platform or module (bigger modification). Since it will be part of XOD (and not an additional library) the code must be GPLv3 as well.
I used to release my code under MIT license, because it's just simple. Thinking about all the requirements of GPLv3 scares me off even if the XOD project itself looks very interesting. I'm currently working on a Project based on the Blockly editor which is more "attractive" from the license point of view...

**Comment by nkrkv** [comment]
The Arduino software part is GPL’ed and it doesn’t hinder those who want to contribute. Although it stops vendors from making a board, taking the IDE and redistribute it in a proprietary fashion. This keeps the ecosystem solid. Our intent is same.

**Comment by Gamadril** [comment]
All right. Thanks for the clarification.
