### ISSUE TITLE
Tab ordering in the Inspector is broken

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#755]
### Steps to reproduce

- Place a `text-lcd-16x2` node
- Click `RS` value input in the Inspector to focus it
- Enter a value (e.g. `8`) and press `TAB`

### Expected behavior

- The cursor moves to the next pin input (`EN`), its text is selected
- I can quickly enter a value → `TAB` → enter value → `TAB` → … → enter value → `ENTER` to bind all pin values.

### Actual behavior

- The focus is lost
- Pressing `TAB` more times brings the focus back to the `RS` input
- Pressing `TAB` again looses focus
- Pressing `TAB` one more time focuses the `EN`’s input
- I have to press `TAB` twice to move to the next input

**Comment by evgenykochetkov** [comment]
Note: this will most likely be quite tedious, because our widgets system has grown into a bit of a mess. For example, the problem causing this specific issue is that almost the whole inspector rerenders after a single value change(see https://github.com/xodio/xod/blob/master/packages/xod-client/src/editor/components/WidgetsGroup.jsx#L11 etc)
All of those problems should be gone after #766

**Comment by nkrkv** [comment]
So now #766 has a clear rationale to be done. I’ll set it as a prerequisite.
